SELECT * FROM pizza_sales;

SELECT SUM(TOTAL_PRICE) AS TOTAL_REVENUE FROM PIZZA_SALES;

SELECT SUM(TOTAL_PRICE) / COUNT(DISTINCT ORDER_ID) AS AVG_ORDER_VALUE FROM PIZZA_SALES;

SELECT SUM(QUANTITY) AS TOTAL_PIZZA_SOLD FROM PIZZA_SALES;

SELECT COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES;

SELECT SUM(QUANTITY) / COUNT(DISTINCT ORDER_ID) AS AVG_PIZZA_PER_ORDER  FROM PIZZA_SALES;

-- HOURLY TREND OF TOTAL PIZZAS SOLD

SELECT HOUR(ORDER_TIME) AS ORDER_HOUR , SUM(QUANTITY) AS TOTAL_PIZZAS_SOLD FROM PIZZA_SALES
GROUP BY HOUR(ORDER_TIME)
ORDER BY HOUR(ORDER_TIME);

-- PIZZA CATEGORY

SELECT PIZZA_CATEGORY , ROUND(SUM(TOTAL_PRICE) * 100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES),2) AS PCT_CATEGORY FROM PIZZA_SALES
GROUP BY PIZZA_CATEGORY;

SELECT PIZZA_SIZE , ROUND(SUM(TOTAL_PRICE) * 100 / (SELECT SUM(TOTAL_PRICE) FROM PIZZA_SALES),2) AS PCT_CATEGORY FROM PIZZA_SALES
GROUP BY PIZZA_SIZE;

-- TOP 5 PIZZA SALES

SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS REVENUE FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY REVENUE DESC
LIMIT 5;

-- BOTTOM 5 PIZZA

SELECT PIZZA_NAME, SUM(TOTAL_PRICE) AS REVENUE FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY REVENUE
LIMIT 5;

-- TOP 5 PIZZA BY QUANTITY

SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY DESC
LIMIT 5;

-- BOTTOM 5 PIZZA BY QUANTITY

SELECT PIZZA_NAME, SUM(QUANTITY) AS TOTAL_QUANTITY FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_QUANTITY
LIMIT 5;

-- TOP 5 PIZZA BY ORDERS

SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS DESC
LIMIT 5;

-- BOTTOM 5 PIZZA BY ORDERS

SELECT PIZZA_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS FROM PIZZA_SALES
GROUP BY PIZZA_NAME
ORDER BY TOTAL_ORDERS 
LIMIT 5;






